Item controllers + services
ProPill/online-pharmacy pull request #10
Opened 2023-10-13 19:26 UTC by byzaya

2023-11-08 12:05 UTC, byzaya commented on src/main/java/org/example/controller/item/ItemInfoController.java
> +  @GetMapping("/info/{item_id}")
<img width="1385" alt="Снимок экрана 2023-11-08 в 15 05 04" src="https://github.com/byzaya/online-pharmacy/assets/75326533/cf5a411a-8748-4cbb-8e02-ebb4e369750d">
<img width="1375" alt="Снимок экрана 2023-11-08 в 15 05 22" src="https://github.com/byzaya/online-pharmacy/assets/75326533/b6c7a1fa-d03e-461c-9227-72ea57145e1f">

2023-11-08 12:11 UTC, byzaya commented on src/main/java/org/example/controller/item/ItemQueryController.java
> +  @GetMapping("/all")
<img width="1396" alt="Снимок экрана 2023-11-08 в 15 11 30" src="https://github.com/byzaya/online-pharmacy/assets/75326533/99d7d11b-6882-427a-86a8-5cbc171ed066">
<img width="1393" alt="Снимок экрана 2023-11-08 в 15 11 49" src="https://github.com/byzaya/online-pharmacy/assets/75326533/da7f80a8-6763-405b-9620-182482e93edc">

2023-11-08 12:30 UTC, byzaya commented on src/main/java/org/example/controller/item/ItemQueryController.java
> +  @GetMapping("/normal/all")
<img width="1392" alt="Снимок экрана 2023-11-08 в 15 30 34" src="https://github.com/byzaya/online-pharmacy/assets/75326533/2843aeea-9d8f-4dc1-962c-b18cb20fa73c">

2023-11-08 13:01 UTC, byzaya commented on src/main/java/org/example/controller/item/ItemQueryController.java
> +  @GetMapping("/doc/all")
<img width="1380" alt="Снимок экрана 2023-11-08 в 15 32 55" src="https://github.com/byzaya/online-pharmacy/assets/75326533/8838c8e2-52ab-4755-b95c-fde0a8efb86f">
<img width="1388" alt="Снимок экрана 2023-11-08 в 15 43 57" src="https://github.com/byzaya/online-pharmacy/assets/75326533/9e463ee7-d720-421c-ab48-d8f33bf842d2">

<img width="1389" alt="Снимок экрана 2023-11-08 в 15 49 03" src="https://github.com/byzaya/online-pharmacy/assets/75326533/997b0c0d-68d3-4f6f-ad61-1df65d2178d6">
<img width="1392" alt="Снимок экрана 2023-11-08 в 16 01 23" src="https://github.com/byzaya/online-pharmacy/assets/75326533/06d3d067-bd94-4957-accb-0b05233da9af">

2023-11-08 13:07 UTC, byzaya commented on src/main/java/org/example/controller/item/ItemQueryController.java
> +  @GetMapping("/type")
<img width="1394" alt="Снимок экрана 2023-11-08 в 16 04 35" src="https://github.com/byzaya/online-pharmacy/assets/75326533/2a309793-02de-402b-843c-02b5797ae600">
<img width="1398" alt="Снимок экрана 2023-11-08 в 16 04 49" src="https://github.com/byzaya/online-pharmacy/assets/75326533/a11b2275-8d51-4444-b904-0ff2c4a5c086">

2023-11-08 13:11 UTC, byzaya commented on src/main/java/org/example/controller/item/ItemQueryController.java
> +  @GetMapping("/type/category")
<img width="1388" alt="Снимок экрана 2023-11-08 в 16 10 52" src="https://github.com/byzaya/online-pharmacy/assets/75326533/5efd104e-4a90-4bf2-b2f6-2ad222f29dc6">
<img width="1390" alt="Снимок экрана 2023-11-08 в 16 11 05" src="https://github.com/byzaya/online-pharmacy/assets/75326533/3e8fdb8e-e067-4558-8541-937aa7050100">

2023-11-08 13:18 UTC, byzaya commented on src/main/java/org/example/controller/item/ItemSearchController.java
> +  @GetMapping("/search_result")
<img width="1391" alt="Снимок экрана 2023-11-08 в 16 17 35" src="https://github.com/byzaya/online-pharmacy/assets/75326533/915713d6-81a5-4c7b-ab8d-136bcf1d9f49">
<img width="1389" alt="Снимок экрана 2023-11-08 в 16 18 13" src="https://github.com/byzaya/online-pharmacy/assets/75326533/0c45151a-4352-421a-b270-72a0c02f24af">

2023-11-08 13:19 UTC, byzaya commented on src/main/java/org/example/controller/item/TypeController.java
> +  @GetMapping("/all")
<img width="1392" alt="Снимок экрана 2023-11-08 в 16 19 03" src="https://github.com/byzaya/online-pharmacy/assets/75326533/5655c15b-3a55-40ad-8271-73446a2fcacb">

2023-11-08 13:19 UTC, byzaya commented on src/main/java/org/example/controller/user/SpecialityController.java
> +  @GetMapping("/all")
<img width="1397" alt="Снимок экрана 2023-11-08 в 16 19 34" src="https://github.com/byzaya/online-pharmacy/assets/75326533/e68b8c3a-6eda-4881-b3f3-5c324b6dcd97">

2023-11-08 13:22 UTC, byzaya commented on src/main/java/org/example/controller/user/SpecialityController.java
> +  @GetMapping("/{user_id}")
<img width="1389" alt="Снимок экрана 2023-11-08 в 16 21 26" src="https://github.com/byzaya/online-pharmacy/assets/75326533/6975ab57-cb91-467e-bd4e-ec375a7edf04">
<img width="1393" alt="Снимок экрана 2023-11-08 в 16 21 42" src="https://github.com/byzaya/online-pharmacy/assets/75326533/9690f25a-77f4-43f6-b4a3-a261462b085f">
<img width="1388" alt="Снимок экрана 2023-11-08 в 16 22 13" src="https://github.com/byzaya/online-pharmacy/assets/75326533/146941bd-e534-4549-9987-2ecab796c75d">

2023-11-08 13:23 UTC, byzaya commented on src/main/java/org/example/controller/item/ItemCreationController.java
> +  @PostMapping("/add")
это надо будет проверить после добавления s3

2023-11-11 08:58 UTC, Lysenko-Aleksandra commented
Необходимо внести изменения в `application.yaml` в соответствии с новыми добавленными кодами(исключениями)

2023-11-11 10:26 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/controller/item/ItemInfoController.java
> +  @GetMapping("/info/{item_id}")
+
в `application.yaml` вроде нет 404, надо добавить

2023-11-11 10:28 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/controller/item/ItemQueryController.java
> +  @GetMapping("/all")
проверила

2023-11-11 10:28 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/controller/item/ItemQueryController.java
> +  @GetMapping("/normal/all")
проверила

2023-11-11 10:29 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/controller/item/ItemQueryController.java
> +  @GetMapping("/doc/all")
проверила 
400 нет в `application.yaml` вроде бы

2023-11-11 10:29 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/controller/item/ItemQueryController.java
> +  @GetMapping("/type")
проверила

2023-11-11 10:29 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/controller/item/ItemQueryController.java
> +  @GetMapping("/type/category")
проверила

2023-11-11 10:31 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/controller/item/ItemSearchController.java
> +  @GetMapping("/search_result")
в `application.yaml `еще есть SEARCH_NOT_FOUND с кодом 404....

2023-11-11 10:44 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/controller/item/TypeController.java
> +  @GetMapping("/all")
проверила

2023-11-11 10:48 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/controller/user/SpecialityController.java
> +  @GetMapping("/all")
проверила

2023-11-11 10:50 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/controller/user/SpecialityController.java
> +  @GetMapping("/{user_id}")
400 и 404 нет в `application.yaml` вроде бы

2023-11-11 10:53 UTC, Lysenko-Aleksandra requested changes
Всё хорошо, нужно только привести `application.yaml` в соответствие с изменениями

2023-11-13 19:34 UTC, byzaya commented on src/main/java/org/example/controller/item/ItemSearchController.java
> +  @GetMapping("/search_result")
ее не будет, я решила, что пустой список будет лучше передавать в таком случае

2023-11-13 19:35 UTC, byzaya commented on src/main/java/org/example/controller/user/SpecialityController.java
> +  @GetMapping("/{user_id}")
404 есть

2023-11-13 19:37 UTC, merged