Order controllers + services
ProPill/online-pharmacy pull request #12
Opened 2023-10-17 21:55 UTC by byzaya

2023-11-11 11:15 UTC, Lysenko-Aleksandra commented
Посмотрю после мержа #10  и  #11

2023-11-11 11:18 UTC, Lysenko-Aleksandra reviewed
Посмотрю после мержа #10 и #11

2023-11-13 20:36 UTC, Lysenko-Aleksandra requested changes

2023-11-13 20:36 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/service/order/OrderService.java
> +      USER_NOT_FOUND.throwException();
нет в `application.yaml`

2023-11-13 20:36 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/service/order/OrderService.java
> +      PHARMACY_NOT_FOUND.throwException();
нет в `application.yaml`

2023-11-13 20:39 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/service/order/OrderService.java
В `application.yaml `сейчас еще есть 404 с наименованием NOT_FOUND(в добавлении заказа).
Я так понимаю, его тоже нужно переименовать или убрать.

2023-11-30 14:18 UTC, Lysenko-Aleksandra commented
Протестирую в `postman`, приложу скрины и откомментирую, если найду несостыковки

2023-12-01 13:19 UTC, lysalexy commented on src/main/java/org/example/controller/order/OrderController.java
> +  @GetMapping("/orders")
![image](https://github.com/byzaya/online-pharmacy/assets/78423459/606f3c28-4223-40b3-b345-1454e685db42)
![image](https://github.com/byzaya/online-pharmacy/assets/78423459/0b4bdf65-9f62-40f5-bef0-6ceb458dbb7b)

2023-12-01 13:21 UTC, Lysenko-Aleksandra commented on src/main/java/org/example/controller/order/OrderController.java
> +      @RequestParam(value = "creation_date") Date creationDate,
Нет прямого указания формата вводимых данных(даты), не могу протестировать

2024-01-05 15:16 UTC, byzaya commented on src/main/java/org/example/controller/order/OrderController.java
> +      @RequestParam(value = "creation_date") Date creationDate,
<img width="1423" alt="Снимок экрана 2024-01-05 в 18 15 34" src="https://github.com/byzaya/online-pharmacy/assets/75326533/481f738e-d9a5-460a-aff9-4b9b1b4ccd12">
<img width="1413" alt="Снимок экрана 2024-01-05 в 18 15 46" src="https://github.com/byzaya/online-pharmacy/assets/75326533/af65f6a8-3ee9-4432-a17d-15ca2b2009a6">
<img width="942" alt="Снимок экрана 2024-01-05 в 18 16 00" src="https://github.com/byzaya/online-pharmacy/assets/75326533/af5bae3a-eaf8-4e19-8191-19ed1b5b460e">
<img width="670" alt="Снимок экрана 2024-01-05 в 18 16 11" src="https://github.com/byzaya/online-pharmacy/assets/75326533/dc7b83e6-0b81-4d39-b9f7-ea84cf332278">

2024-01-05 16:11 UTC, Lysenko-Aleksandra approved these changes

2024-01-05 16:16 UTC, merged